use unicode_general_category::{get_general_category, GeneralCategory as GC};
use wasm_bindgen::prelude::*;

// `COVERED_RANGES`: inclusive code-point ranges the bundled woff2 glyph fonts
// render to a real (non-.notdef) glyph, intersected with the printable
// whitelist — the "no tofu" set. Generated by `tools/planner` (committed);
// `tools/verify_fonts.py` proves it equals what the served fonts actually cover.
include!("coverage.rs");

/// Return a single random *printable, renderable* Unicode character.
///
/// Uniformly samples a code point in U+0000..=U+10FFFF (skipping the surrogate
/// gap) and keeps it only if it is BOTH a visibly printable category
/// (`is_printable_char`) AND covered by a bundled font (`is_covered`). The
/// second condition guarantees the result renders without a tofu box (□) in the
/// bundled `AppGlyph` font.
#[wasm_bindgen]
pub fn random_printable_char() -> String {
    loop {
        // js_sys::Math::random() -> f64 in [0, 1); scale to the full code space.
        let cp = (js_sys::Math::random() * 1_114_112.0) as u32;
        if (0xD800..=0xDFFF).contains(&cp) {
            continue; // surrogate gap: not scalar values
        }
        if let Some(c) = char::from_u32(cp) {
            if is_printable_char(c) && is_covered(c) {
                return c.to_string();
            }
        }
    }
}

/// Public, reusable classifier: is `c` a visibly printable Unicode glyph?
///
/// Thin wrapper over the `is_printable` General_Category whitelist so callers
/// (and tests) can reuse the exact same printability rule the sampler uses,
/// without depending on the random draw.
pub fn is_printable_char(c: char) -> bool {
    is_printable(get_general_category(c))
}

/// Is `c` covered by a bundled font (i.e. renders to a non-.notdef glyph)?
///
/// `COVERED_RANGES` is generated from the bundled woff2 fonts by `tools/planner`,
/// so this is exactly the set the frontend can draw without tofu. The sampler
/// intersects this with `is_printable_char`. `tools/verify_fonts.py` (run in CI)
/// re-reads the served woff2 chunks and asserts their union equals these ranges,
/// so the table can never drift from the fonts.
pub fn is_covered(c: char) -> bool {
    let cp = c as u32;
    COVERED_RANGES
        .binary_search_by(|&(lo, hi)| {
            use std::cmp::Ordering::{Greater, Less};
            if cp < lo {
                Greater
            } else if cp > hi {
                Less
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

/// Whitelist of General_Category values that render as a standalone glyph.
///
/// Everything else is rejected: Control / Format / Surrogate / PrivateUse /
/// Unassigned, the Line/Paragraph/Space separators, the combining marks
/// (Mn/Mc/Me, which have no standalone glyph), and any future #[non_exhaustive]
/// category. SpaceSeparator (incl. U+0020) is excluded so a press never looks
/// like it did nothing; add it here if a visible blank is acceptable.
fn is_printable(g: GC) -> bool {
    matches!(
        g,
        GC::UppercaseLetter
            | GC::LowercaseLetter
            | GC::TitlecaseLetter
            | GC::ModifierLetter
            | GC::OtherLetter
            | GC::DecimalNumber
            | GC::LetterNumber
            | GC::OtherNumber
            | GC::ConnectorPunctuation
            | GC::DashPunctuation
            | GC::OpenPunctuation
            | GC::ClosePunctuation
            | GC::InitialPunctuation
            | GC::FinalPunctuation
            | GC::OtherPunctuation
            | GC::MathSymbol
            | GC::CurrencySymbol
            | GC::ModifierSymbol
            | GC::OtherSymbol
    )
}

// HOST tests. These run under plain `cargo test` on the native target.
//
// IMPORTANT: do NOT call `random_printable_char()` here. It uses
// `js_sys::Math::random()`, which panics on the native target. The classifier
// (`is_printable_char` / `is_printable`) and `char::from_u32` are pure and
// safe to exercise natively. The real exported sampler is tested under wasm in
// `tests/wasm.rs` (run via `wasm-pack test --node`). The font-coverage guarantee
// (every emittable code point renders) lives in `tools/verify_fonts.py`, which
// reads the served woff2 directly (Rust can't parse woff2).
#[cfg(test)]
mod tests {
    use super::{is_covered, is_printable, is_printable_char, COVERED_RANGES};
    use unicode_general_category::{get_general_category, GeneralCategory as GC};

    /// Every ALLOWED General_Category has a representative that is printable.
    #[test]
    fn allowed_categories_are_printable() {
        // (representative char, expected category label) for the whitelist.
        let allowed = [
            ('\u{0041}', "Lu UppercaseLetter"),
            ('\u{0061}', "Ll LowercaseLetter"),
            ('\u{01C5}', "Lt TitlecaseLetter"),
            ('\u{02B0}', "Lm ModifierLetter"),
            ('\u{6F22}', "Lo OtherLetter"),
            ('\u{0035}', "Nd DecimalNumber"),
            ('\u{2167}', "Nl LetterNumber"),
            ('\u{00BD}', "No OtherNumber"),
            ('\u{005F}', "Pc ConnectorPunctuation"),
            ('\u{002D}', "Pd DashPunctuation"),
            ('\u{0028}', "Ps OpenPunctuation"),
            ('\u{0029}', "Pe ClosePunctuation"),
            ('\u{2018}', "Pi InitialPunctuation"),
            ('\u{2019}', "Pf FinalPunctuation"),
            ('\u{0021}', "Po OtherPunctuation"),
            ('\u{002B}', "Sm MathSymbol"),
            ('\u{0024}', "Sc CurrencySymbol"),
            ('\u{005E}', "Sk ModifierSymbol"),
            ('\u{00A9}', "So OtherSymbol"),
        ];
        for (c, label) in allowed {
            assert!(
                is_printable_char(c),
                "{c:?} (U+{:04X}, {label}) should be printable",
                c as u32
            );
        }
    }

    /// Spot-check that `get_general_category` actually maps a few of the
    /// allowed representatives to the General_Category we expect.
    #[test]
    fn allowed_representatives_have_expected_category() {
        assert_eq!(get_general_category('\u{0041}'), GC::UppercaseLetter, "U+0041 is Lu");
        assert_eq!(get_general_category('\u{0061}'), GC::LowercaseLetter, "U+0061 is Ll");
        assert_eq!(get_general_category('\u{01C5}'), GC::TitlecaseLetter, "U+01C5 is Lt");
        assert_eq!(get_general_category('\u{2167}'), GC::LetterNumber, "U+2167 is Nl");
        assert_eq!(get_general_category('\u{00BD}'), GC::OtherNumber, "U+00BD is No");
        assert_eq!(get_general_category('\u{0024}'), GC::CurrencySymbol, "U+0024 is Sc");
        // And the whitelist agrees the mapped category is printable.
        assert!(is_printable(get_general_category('\u{0041}')), "Lu must be printable");
        assert!(is_printable(get_general_category('\u{0024}')), "Sc must be printable");
    }

    /// Every REJECTED category has a representative that is NOT printable.
    #[test]
    fn rejected_categories_are_not_printable() {
        let rejected = [
            ('\u{0000}', "Cc Control (NUL)"),
            ('\u{000A}', "Cc Control (LF)"),
            ('\u{00AD}', "Cf Format (SHY)"),
            ('\u{E000}', "Co PrivateUse"),
            ('\u{0378}', "Cn Unassigned"),
            ('\u{2028}', "Zl LineSeparator"),
            ('\u{2029}', "Zp ParagraphSeparator"),
            ('\u{0020}', "Zs SpaceSeparator (SPACE)"),
            ('\u{00A0}', "Zs SpaceSeparator (NBSP)"),
            ('\u{0301}', "Mn NonspacingMark"),
            ('\u{0903}', "Mc SpacingMark"),
            ('\u{20DD}', "Me EnclosingMark"),
        ];
        for (c, label) in rejected {
            assert!(
                !is_printable_char(c),
                "{c:?} (U+{:04X}, {label}) should be rejected",
                c as u32
            );
        }
    }

    /// Spot-check that a couple of rejected representatives map to the
    /// General_Category we expect.
    #[test]
    fn rejected_representatives_have_expected_category() {
        assert_eq!(get_general_category('\u{0000}'), GC::Control, "U+0000 is Cc");
        assert_eq!(get_general_category('\u{00AD}'), GC::Format, "U+00AD is Cf");
        assert_eq!(get_general_category('\u{E000}'), GC::PrivateUse, "U+E000 is Co");
        assert_eq!(get_general_category('\u{0378}'), GC::Unassigned, "U+0378 is Cn");
        assert_eq!(get_general_category('\u{2028}'), GC::LineSeparator, "U+2028 is Zl");
        assert_eq!(get_general_category('\u{2029}'), GC::ParagraphSeparator, "U+2029 is Zp");
        assert_eq!(get_general_category('\u{0020}'), GC::SpaceSeparator, "U+0020 is Zs");
        assert_eq!(get_general_category('\u{0301}'), GC::NonspacingMark, "U+0301 is Mn");
        assert_eq!(get_general_category('\u{0903}'), GC::SpacingMark, "U+0903 is Mc");
        assert_eq!(get_general_category('\u{20DD}'), GC::EnclosingMark, "U+20DD is Me");
    }

    /// `char::from_u32` boundary behavior around the surrogate gap and the
    /// upper scalar limit — the exact invariants the sampler relies on.
    #[test]
    fn char_from_u32_boundaries() {
        assert!(char::from_u32(0xD7FF).is_some(), "U+D7FF is a valid scalar");
        assert!(char::from_u32(0xE000).is_some(), "U+E000 is a valid scalar");
        assert!(char::from_u32(0x10FFFF).is_some(), "U+10FFFF is the max scalar");

        assert!(char::from_u32(0xD800).is_none(), "U+D800 (surrogate) is not a char");
        assert!(char::from_u32(0xDFFF).is_none(), "U+DFFF (surrogate) is not a char");
        assert!(char::from_u32(0x110000).is_none(), "0x110000 exceeds the scalar range");
    }

    /// The generated coverage table must be non-empty, sorted, and strictly
    /// disjoint, which is what `is_covered`'s binary search relies on.
    #[test]
    fn coverage_ranges_are_sorted_and_disjoint() {
        assert!(!COVERED_RANGES.is_empty(), "coverage table is unexpectedly empty");
        let mut prev_hi: Option<u32> = None;
        for &(lo, hi) in COVERED_RANGES {
            assert!(lo <= hi, "range (0x{lo:X}, 0x{hi:X}) is inverted");
            assert!(hi <= 0x10FFFF, "range end 0x{hi:X} exceeds the scalar range");
            if let Some(p) = prev_hi {
                // Merged ranges are separated by >= 1 uncovered code point.
                assert!(lo > p + 1, "ranges not disjoint/merged near 0x{lo:X} (prev hi 0x{p:X})");
            }
            prev_hi = Some(hi);
        }
    }

    /// `is_covered` agrees with the generated table for a few hand-picked points.
    #[test]
    fn is_covered_spot_checks() {
        assert!(is_covered('\u{0041}'), "U+0041 'A' must be covered");
        assert!(is_covered('\u{6F22}'), "U+6F22 '漢' must be covered (CJK)");
        // U+10FFFF is a noncharacter at the top of the scalar range; no font
        // ships a glyph for it.
        assert!(!is_covered('\u{10FFFF}'), "U+10FFFF must not be covered");
    }
}
