// One generated stylesheet declares ~150 @font-face rules, all sharing the
// single family "AppGlyph" and each scoped to its own unicode-range. The browser
// treats them as one font and fetches only the woff2 chunk a character needs.
// Generated by tools/build_fonts.py from the deduped, subsetted Noto sources.
import "./fonts/gen/glyph-fonts.css";

/** The single glyph font-family. No system fallback: a coverage bug stays visible. */
export const GLYPH_FONT_STACK = '"AppGlyph"';

/**
 * Ensure the woff2 chunk that renders `ch` is loaded before we display it, so a
 * covered character never flashes as a tofu box. Safe everywhere: it no-ops when
 * the Font Loading API is unavailable (e.g. jsdom) and never rejects, so a font
 * load failure can't block the UI.
 */
export async function ensureGlyph(ch: string): Promise<void> {
  const fonts = document.fonts;
  if (!fonts?.load) return;
  try {
    await fonts.load(`64px ${GLYPH_FONT_STACK}`, ch);
  } catch {
    // A font-load failure must not block rendering; the glyph still shows.
  }
}
