#!/usr/bin/env python3
"""fontTools half of the hybrid font pipeline.

Reads tools/plan.json (produced by the Rust planner), and for each source font:
  1. instances variable axes to a single weight (wght=400, wdth=100) — big size win,
  2. subsets it to exactly the code points the planner assigned it (deduped),
  3. saves it as a woff2 chunk in frontend/src/fonts/gen/.

Also writes frontend/src/fonts/gen/glyph-fonts.css: one @font-face per chunk, all
sharing the single family "AppGlyph", each scoped to its `unicode-range`. The
browser then treats them as one font, fetching only the chunk a given character
needs.

Run from the repo root (after the planner):
    tools/.venv/bin/python tools/build_fonts.py
"""

import json
import os
import sys

from fontTools.ttLib import TTFont
from fontTools.subset import Options, Subsetter
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SRC_DIR = os.path.join(ROOT, "tools", "sources")
OUT_DIR = os.path.join(ROOT, "frontend", "src", "fonts", "gen")
FAMILY = "AppGlyph"


def fmt_range(lo, hi):
    return f"U+{lo:04X}" if lo == hi else f"U+{lo:04X}-{hi:04X}"


def instance_static(tt):
    """Pin variable axes to a regular instance (no-op for static fonts)."""
    if "fvar" not in tt:
        return
    axes = {}
    for a in tt["fvar"].axes:
        if a.axisTag == "wght":
            axes["wght"] = min(max(400.0, a.minValue), a.maxValue)
        elif a.axisTag == "wdth":
            axes["wdth"] = min(max(100.0, a.minValue), a.maxValue)
        else:
            axes[a.axisTag] = a.defaultValue
    instantiateVariableFont(tt, axes, inplace=True)


def make_options():
    opt = Options()
    opt.flavor = "woff2"
    opt.hinting = False
    opt.desubroutinize = True
    opt.glyph_names = False
    opt.legacy_kern = False
    opt.layout_features = []  # single isolated glyphs: no shaping needed
    opt.notdef_outline = False
    opt.recalc_bounds = False
    opt.recalc_timestamp = False
    opt.name_IDs = []
    opt.name_legacy = False
    opt.drop_tables += ["DSIG"]
    opt.ignore_missing_glyphs = True
    opt.ignore_missing_unicodes = True
    return opt


def main():
    with open(os.path.join(ROOT, "tools", "plan.json")) as f:
        plan = json.load(f)

    os.makedirs(OUT_DIR, exist_ok=True)
    # Clean stale chunks so the gen/ dir always matches the current plan.
    for name in os.listdir(OUT_DIR):
        if name.endswith(".woff2") or name == "glyph-fonts.css":
            os.remove(os.path.join(OUT_DIR, name))

    faces = []
    total_bytes = 0
    for i, entry in enumerate(plan["fonts"]):
        src = os.path.join(SRC_DIR, entry["file"])
        ranges = entry["ranges"]
        unicodes = []
        for lo, hi in ranges:
            unicodes.extend(range(lo, hi + 1))

        tt = TTFont(src)
        try:
            instance_static(tt)
        except Exception as e:  # noqa: BLE001 — keep coverage; just ship variable
            print(f"  warn: instancing {entry['file']} failed ({e}); subsetting as-is")

        ss = Subsetter(options=make_options())
        ss.populate(unicodes=unicodes)
        ss.subset(tt)

        chunk = f"chunk{i:03d}.woff2"
        out = os.path.join(OUT_DIR, chunk)
        tt.flavor = "woff2"
        tt.save(out)
        total_bytes += os.path.getsize(out)

        urange = ",".join(fmt_range(lo, hi) for lo, hi in ranges)
        faces.append((chunk, urange))
        if i % 20 == 0 or i == len(plan["fonts"]) - 1:
            print(f"  [{i + 1}/{len(plan['fonts'])}] {chunk}  {len(unicodes)} cps")

    css = ["/* @generated by tools/build_fonts.py — DO NOT EDIT. */"]
    for chunk, urange in faces:
        css.append(
            "@font-face {\n"
            f'  font-family: "{FAMILY}";\n'
            f'  src: url("./{chunk}") format("woff2");\n'
            f"  unicode-range: {urange};\n"
            "  font-display: swap;\n"
            "}"
        )
    with open(os.path.join(OUT_DIR, "glyph-fonts.css"), "w") as f:
        f.write("\n".join(css) + "\n")

    print(
        f"\nbuilt {len(faces)} woff2 chunks, "
        f"{total_bytes / 1048576:.2f} MB total -> {OUT_DIR}"
    )


if __name__ == "__main__":
    sys.exit(main())
